### ISSUE TITLE
Error while running build-static-with-db48.sh

### ISSUE THREAD

**Issue by dogukanucak** [fflo/sixeleven#2]
`In file included from headers.h:99:0,
                 from auxpow.cpp:4:
bignum.h:49:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/buffer.h:13:0,
                 from headers.h:41,
                 from auxpow.cpp:4:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from headers.h:99:0,
                 from auxpow.cpp:4:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:54:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
                     ^
bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
bignum.h:59:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
                     ^
bignum.h:60:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
bignum.h:62:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
bignum.h: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
bignum.h:69:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
bignum.h: In destructor ‘CBigNum::~CBigNum()’:
bignum.h:76:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);
`
And more like this in the same file because of BigNum error in Linux version. How can I fix it?

**Comment by fflo** [comment]
what OS are you using?

**Comment by dogukanucak** [comment]
Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux

**Comment by fflo** [comment]
Ok. Seems to me that this issue is related to the new openssl version of Debian stretch:

From the openssl documentation:

    BN_init() was removed in OpenSSL 1.1.0; use BN_new() instead.

Please gimme some time to patch the code to avoid the the removed SSL apis.

**Comment by fflo** [comment]
@dogukanucak SixEleven bignum.h relies heavily on routines which have been removed in OpenSSL 1.1.x.
This problem seems to be a know issue for many other projects:
- [Bitcoin bitnum.h removal commit](https://github.com/laanwj/bitcoin/commit/4ec3561eb3473638230ef780b41343bc6284b460) and
- [Bitcoin bitnum.h removal files](https://github.com/bitcoin/bitcoin/pull/7095/files)
- [rethinkdb bitnum rewrite](https://github.com/rethinkdb/rethinkdb/commit/624561559daf692583c375d84838d34e28798c66)
- [OpenSSL 1.1.x BN_new manual](https://www.openssl.org/docs/man1.1.0/crypto/BN_new.html)

Therefore to resolve this problem using Debian Linux 9 (Stretch) I recommend you to use the latest stable OpenSSL 1.0.x libraries using:
``
apt install libssl1.0-dev
``

**Comment by dogukanucak** [comment]
thank you it solved the errors, however I received one last error;
`serialize.h:400:7: error: ‘const class std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, long long unsigned int>’ has no member named ‘Serialize’
     a.Serialize(os, (int)nType, nVersion);
     ~~^~~~~~~~~
Makefile:107: recipe for target 'obj/nogui/walletdb.o' failed
make: *** [obj/nogui/walletdb.o] Error 1
`

**Comment by fflo** [comment]
Ack. I can reproduce this issue. To bugfix this issue (and some others) please pull the latest code of SixEleven from GitHub and retry.
``cat doc/build-linux.txt`` has been updated with the latest compile instructions.
