### ISSUE TITLE
Documentation About Block Structure

### ISSUE THREAD

**Issue by dogukanucak** [fflo/sixeleven#3]
Hello, I am working on a script to parse coming data. Is there any document about how I can parse the block properly from the received  binary TCP data?

**Comment by fflo** [comment]
Did you already take a look at https://github.com/fflo/sixeleven-abe block explorer?

It supports parsing the blockchain data using the blk.... files in the data directory and the 611d rpc api.

**Comment by dogukanucak** [comment]
Yes I have taken look at there, I believe I do not have enough technical knowledge to understand it. Could you please give me just one example of a SixEleven data and how to parse and validate it? Thank you for your time.

**Comment by fflo** [comment]
Hi Deniz, Hi Dogukan,

actually it seems you have already successfully decoded the raw packet structure of 611 coin:
https://github.com/dogukanucak/PA193_test_parser_SixEleven

Congratulation for your great work: https://github.com/dogukanucak/PA193_test_parser_SixEleven/raw/master/611.pdf

Is it also possible to extract the public JSON encoded DNS settings from the 611 blockchain using your Java parser?

Another interesting scientific document about _Namecoin_ was published from Andreas Loibl, _TUM_ which also applies to this project: https://www.net.in.tum.de/fileadmin/TUM/NET/NET-2014-08-1/NET-2014-08-1_14.pdf

**Comment by dogukanucak** [comment]
> Is it also possible to extract the public JSON encoded DNS settings from the 611 blockchain using your Java parser?

Could you please redirect your question as an issue into my repository? I am appereciated that you like the project and would like to improve according to your guideness

**Comment by fflo** [comment]
Sure. Done.
